### PR TITLE
fix(react/utils): added useProxy parameter for opts #683

### LINKED ISSUE #683: allow `useProxy` to pass `useSnapshot` options
## Summary

`useProxy` only takes the store yet as argument, in case of input-elements a sync pass-through would also be required (ref https://github.com/pmndrs/valtio/#update-synchronously)

## Link to reproduction

https://stackblitz.com/edit/vitejs-vite-6d3nla?file=src%2FApp.jsx&terminal=dev

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/valtio/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

### PR DESCRIPTION
**Pull request by steve-py96**
## Related Issues or Discussions

Fixes #683

## Summary

pass-through `useSnapshot` opts in `useProxy`

## Check List

- [x ] `yarn run prettier` for formatting code and docs

### CODE REVIEW

File: src/react/utils/useProxy.ts [hunk 1]
```diff
@@ -19,10 +19,14 @@ import { useSnapshot } from 'valtio/react'
...
  *
  * @param proxy
+ * @param options
  * @returns A new proxy which you can use in the render as well as in callbacks.
  */
-export function useProxy<T extends object>(proxy: T): T {
-  const snapshot = useSnapshot(proxy) as T
+export function useProxy<T extends object>(
+  proxy: T,
+  options?: Parameters<typeof useSnapshot<T>>[1]
```
Comment (steve-py96) [inline src/react/utils/useProxy.ts:27]: for older ts versions probably without <T> for useSnapshot, I'll remove that

File: src/react/utils/useProxy.ts [hunk 2]
```diff
@@ -19,10 +19,14 @@ import { useSnapshot } from 'valtio/react'
...
  *
  * @param proxy
+ * @param options
  * @returns A new proxy which you can use in the render as well as in callbacks.
  */
-export function useProxy<T extends object>(proxy: T): T {
-  const snapshot = useSnapshot(proxy) as T
+export function useProxy<T extends object>(
+  proxy: T,
+  options?: Parameters<typeof useSnapshot>[1]
```
Comment (dai-shi) [inline src/react/utils/useProxy.ts:27]: To be precise, let's do this:
```suggestion
  options?: NonNullable<Parameters<typeof useSnapshot>[1]>
```

**Review by dai-shi — APPROVED** [review]
LGTM

File: src/react/utils/useProxy.ts (hunk 2 above)
Comment (steve-py96) [reply src/react/utils/useProxy.ts]: I don't mind going safe here ofc 👍🏿  (but since I wanna learn possible edge-cases and got not much experience in OSS (unlike you :P) I ask: Is `null` even a possible arg value here? When I f.e. try to assign null as Parameter it doesn't work)

Comment (dai-shi) [reply src/react/utils/useProxy.ts]: It's to avoid `undefined`. There's no runtime risk to pass `undefined`. It's just to make the `useProxy` type same as `useSnapshot` type.
